---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Dictionary

```{r}
#| include: false
library(tidyverse)
```


This is a [@kadagidze84] dictionary with some additions from Diana Kakashvili and Jesse Wichers Schreur. It still need some polishing. Download in [`.csv`](https://raw.githubusercontent.com/agricolamz/tsova_tush_fst/refs/heads/main/data/kk_merged.csv) or [`.xslx`](https://raw.githubusercontent.com/agricolamz/tsova_tush_fst/refs/heads/main/data/kk_merged.xlsx) format. Use the `Extended version` in order to see all fields, and don't forget to scroll to the right in order to see some hidden columns.

::: {.panel-tabset}

### Short version

```{r}
#| echo: false
#| warning: false

library(tidyverse)
library(DT)

read_csv("data/kk_merged.csv") |> 
  mutate(gender_la = if_else(is.na(gender_la) & sharedgrammaticalinfo %in% c("vt", "vi", "adv", "ptcp", "num", "pro interrog", "pro", "pro poss", "pro indef"), sharedgrammaticalinfo, gender_la)) |> 
  select(lemma_la, gender_la, en, ka, ru) |> 
  rename(lemma = lemma_la, 
         grammar = gender_la) |> 
  mutate(grammar = factor(grammar)) |> 
  datatable(filter = 'top', escape = FALSE, rownames = FALSE,
            options = list(pageLength = 20, dom = 'ftop'))
```

### Extended version

```{r}
#| echo: false
#| warning: false

library(tidyverse)
library(DT)

read_csv("data/kk_merged.csv") |> 
    datatable(filter = 'top', escape = FALSE, rownames = FALSE,
              options = list(pageLength = 20, dom = 'ftop'))
```

:::