---
output: html_document
editor_options: 
  chunk_output_type: console
code-block-bg: true
code-block-border-left: "#31BAE9"
---

# Tsova Tush tools

In order to use this tools you need to open a Google Colaboratory file. 

- Open your Google Drive <https://drive.google.com>
- Click `New` at the left corner
- In the list of possible formats choose `More` and find Google Colaboratory
- In case you can't see it, press `Add more application`, type Google Colaboratory and agree to install it to your Google Drive. Then try to open Google Colaboratory blank file as described in the previous bullet.
- Paste the following code press the `Play` button and wait about 20-30 seconds.

```{.bash}
!git clone -q https://github.com/agricolamz/tsova_tush_fst_tools.git; mv tsova_tush_fst_tools/* .; rm -d tsova_tush_fst_tools; make -s requirements; make
```

- In order to transcribe from mkherduli to latin you need to use the following command (*at't'iv* means 'fate, luck')

```{.bash}
!make mkherduli_transcription INPUT="ატტივ" 
```

```
at't'iv
```

- In order to transcribe from latin to mkherduli you need to use the following command (*pħe* means 'village')[^comment]

[^comment]: You need to be aware that there are multiple ways typing ŏ, t' etc. If you have problems, copy from the transliteration section.

```{.bash}
!make latin_transcription INPUT="pħe" 
```

```
ფჰ'ე
```

- In order to gloss you need to use the following command[^glossing_problems] (*txon psarlujn xi co doɁmak’ine.* means 'We couldn’t bring water tonight.', see [@wichersschreur2025: 202]):

[^glossing_problems]: This is just a preliminary tool. There are some known problems that are listed in [the following file](https://github.com/agricolamz/tsova_tush_fst_tools/blob/main/PROBLEMS.md). 

```{.bash}
!make glossing INPUT="txon psarlujn xi co doɁmak’ine."
```

```
txo-n      1.pl.excl-dat
psarluj-n  psarlo.N.JJ.pl-dat
xi         xi.N.DD.abs
xi         xi.N.DD.obl.ess
xi         xi.N.DD.obl.in.ess
xi         xi.N.DD.obl.in.lat
xi         xi.N.DD.obl.lat
+?         co
+?         doɁmakʼine
```

- In order to generate forms you need to use the following command using triangle brackets for each gloss and using `>` as a morpheme boundary  (*kʼnat* means 'boy' or 'son'):

```{.bash}
!make generation INPUT="kʼnat<N><VB><pl>><gen>"
```

```
kʼnat.N.VB.pl-gen	kʼnata-ⁿ
kʼnat.N.VB.pl-gen	kʼnati-ⁿ
```

- In order to see all possible forms for some lemma you can run a substring search. In order to do it, all symbols should be separated by spaces, all tags should be surrounded by `%<...%>` (*kʼnat* means 'boy' or 'son'):

```{.bash}
!make substring_search INPUT="k ʼ n a t %<N%> ?*"
```

```
hfst-compose-intersect: Warning: 
Found output symbols (e.g. "@_IDENTITY_SYMBOL_@") in transducer in
file <stdin> which will be filtered out because they are
not found on the input tapes of transducers in file
bbl_generator.hfst.

kʼnata-ⁿ        kʼnat.N.VB.pl-gen
kʼnata-x        kʼnat.N.VB.pl-cont
kʼnate-ciⁿ      kʼnat.N.VB.obl-apud.ess
kʼnate-ğ        kʼnat.N.VB.obl-in.trans
kʼnate-ğ        kʼnat.N.VB.obl-trans
kʼnate-go-ğ     kʼnat.N.VB.obl-ad-trans
kʼnate-go       kʼnat.N.VB.obl-ad.ess
kʼnate-gŏ       kʼnat.N.VB.obl-ad.lat
kʼnate-go-mciⁿ  kʼnat.N.VB.obl-ad-term
kʼnate-go-reⁿ   kʼnat.N.VB.obl-ad-abl
kʼnate-guiħ     kʼnat.N.VB.obl-apud.lat
kʼnate-i-ğ      kʼnat.N.VB.obl-in-trans
kʼnate-i        kʼnat.N.VB.obl-in.ess
kʼnate-i        kʼnat.N.VB.obl-in.lat
kʼnate-i-mciⁿ   kʼnat.N.VB.obl-in-term
kʼnate-i-reⁿ    kʼnat.N.VB.obl-in-abl
kʼnate          kʼnat.N.VB.obl.ess
kʼnate          kʼnat.N.VB.obl.in.ess
kʼnate          kʼnat.N.VB.obl.in.lat
kʼnate          kʼnat.N.VB.obl.lat
kʼnate-lo-ğ     kʼnat.N.VB.obl-inter-trans
kʼnate-lo       kʼnat.N.VB.obl-inter.ess
kʼnate-lŏ       kʼnat.N.VB.obl-inter.lat
kʼnate-lo-mciⁿ  kʼnat.N.VB.obl-inter-term
kʼnate-lo-reⁿ   kʼnat.N.VB.obl-inter-abl
kʼnate-mciⁿ     kʼnat.N.VB.obl-in.term
kʼnate-mciⁿ     kʼnat.N.VB.obl-term
kʼnate-n        kʼnat.N.VB.obl-dat
kʼnate-ⁿ        kʼnat.N.VB.obl-gen
kʼnate-reⁿ      kʼnat.N.VB.obl-abl
kʼnate-reⁿ      kʼnat.N.VB.obl-in.abl
kʼnate-s        kʼnat.N.VB.obl-erg
kʼnate-v        kʼnat.N.VB.obl-ins
kʼnate-xiⁿ      kʼnat.N.VB.obl-apud.abl
kʼnate-x        kʼnat.N.VB.obl-cont
kʼnati-ciⁿ      kʼnat.N.VB.pl-apud.ess
kʼnati-ğ        kʼnat.N.VB.pl-in.trans
kʼnati-ğ        kʼnat.N.VB.pl-trans
kʼnati-go-ğ     kʼnat.N.VB.pl-ad-trans
kʼnati-go       kʼnat.N.VB.pl-ad.ess
kʼnati-gŏ       kʼnat.N.VB.pl-ad.lat
kʼnati-go-mciⁿ  kʼnat.N.VB.pl-ad-term
kʼnati-go-reⁿ   kʼnat.N.VB.pl-ad-abl
kʼnati-guiħ     kʼnat.N.VB.pl-apud.lat
kʼnati-i-mciⁿ   kʼnat.N.VB.pl-in-term
kʼnati          kʼnat.N.VB.abs.pl
kʼnati          kʼnat.N.VB.pl.ess
kʼnati          kʼnat.N.VB.pl.in.ess
kʼnati          kʼnat.N.VB.pl.in.lat
kʼnati          kʼnat.N.VB.pl.lat
kʼnati-lo-ğ     kʼnat.N.VB.pl-inter-trans
kʼnati-lo       kʼnat.N.VB.pl-inter.ess
kʼnati-lŏ       kʼnat.N.VB.pl-inter.lat
kʼnati-lo-mciⁿ  kʼnat.N.VB.pl-inter-term
kʼnati-lo-reⁿ   kʼnat.N.VB.pl-inter-abl
kʼnati-mciⁿ     kʼnat.N.VB.pl-in.term
kʼnati-mciⁿ     kʼnat.N.VB.pl-term
kʼnati-n        kʼnat.N.VB.pl-dat
kʼnati-ⁿ        kʼnat.N.VB.pl-gen
kʼnati-reⁿ      kʼnat.N.VB.pl-abl
kʼnati-reⁿ      kʼnat.N.VB.pl-in.abl
kʼnati-v        kʼnat.N.VB.pl-erg
kʼnati-v        kʼnat.N.VB.pl-ins
kʼnati-xiⁿ      kʼnat.N.VB.pl-apud.abl
kʼnati-x        kʼnat.N.VB.pl-cont
kʼnat           kʼnat.N.VB.abs
```
